In [1]:
import numpy as np

img = np.random.randint(0, 10, (3,4))
mean = np.sum(img).reshape(1, -1)
img - mean
print(img)
print(mean)


[[9 0 4 9]
 [3 6 8 2]
 [2 3 1 0]]
[[4.66666667 3.         4.33333333 3.66666667]]


In [30]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,0],[0,1]])
np.matmul(a,b)

array([[1, 2],
       [3, 4]])