In [35]:
import cv2
import numpy as np

def rms(img1, img2):
    # This function calculates RMS error between two grayscale images. 
    # Two images should have same sizes.
    if (img1.shape[0] != img2.shape[0]) or (img1.shape[1] != img2.shape[1]):
        raise Exception("img1 and img2 should have the same sizes.")

    diff = np.abs(img1.astype(np.int32) - img2.astype(np.int32))

    return np.sqrt(np.mean(diff ** 2))


import random

In [3]:
original = cv2.imread('bird.jpg', cv2.IMREAD_GRAYSCALE)

gaussian = add_gaussian_noise(original.copy())
print("RMS for Gaussian noise:", rms(original, gaussian))
cv2.imwrite('gaussian.jpg', gaussian)

RMS for Gaussian noise: 0.0


True

In [15]:
g1 = np.array([True, False, True, False])
g2 = np.array([True, True, False, False])
go = np.logical_and(g1, g2)

print(go)

[ True False False False]


In [31]:
H, W = original.shape
noise = np.random.normal(0, 16, H*W).reshape(H, W)
gaussian = original + noise

cv2.imshow('img', gaussian)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [32]:
cv2.imwrite('gaussian.jpg', gaussian)

True

In [34]:
original.std()

29.91027660796907

In [62]:
samples = 50

image = np.random.randint(0, 256, samples)

zeros = np.random.choice([0, 0.3, 0.6], samples, p=(0.1, 0.1, 0.8))
image = image * zeros.round()
highs = ( np.ones(samples) - (zeros*2).round() ) * 255
image = image + highs

print(image)

[ 13.   0. 221. 255. 208. 181. 125. 220. 255. 105. 248.   0. 119.  37.
 131. 249.  33. 255.   0. 158.  41. 149.  85. 130. 141.   0.  74. 219.
   3. 139. 253.   8. 102. 159. 231.   2.  94. 255. 118. 161.  43. 255.
  46. 221. 233.  92. 177.   0. 159. 255.]


In [50]:
round(1.5)

2

In [59]:
samples = 10000
hi = np.random.uniform(0, 2.5, samples)
hi = (hi.round() * 0.7).round()
print(np.max(hi), np.min(hi), np.sum(hi))

print(hi)

1.0 0.0 8016.0
[1. 1. 1. ... 1. 0. 1.]


In [17]:
tast = (1, 2, 3)
len(tast)

3

In [40]:
import numpy as np
hoe = np.array([[3,4,7], [5,6, 0]])
H, W = hoe.shape
K = int((3 - 1)/2)
hie = np.zeros((H+(2*K), W+(2*K)))

hie[K:H+K,K:W+K] = hoe

print(hie)

[[0. 0. 0. 0. 0.]
 [0. 3. 4. 7. 0.]
 [0. 5. 6. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [39]:
(2*K)

2.0

In [42]:
kern = 5
K = int((kern-1)/2)
dx = {np.ones(kern)*(K-i) for i in range(kern)}

TypeError: unhashable type: 'numpy.ndarray'

In [43]:
np.zeros(3)

array([0., 0., 0.])

In [46]:
import cv2
jj = cv2.imread('./test_images/cat_noisy.jpg')

H, W, C = jj.shape

In [47]:
print(H ,W ,C)

427 640 3


In [58]:
kernel_size = 5

hh = np.random.randint(1, 10, (2, 6, 3))
print(hh)

h1 = hh.transpose(2, 0, 1)
print(h1)

h2 = h1.reshape(3, )
print(h2)

[[[6 4 7]
  [1 6 3]
  [4 4 2]
  [1 1 2]
  [1 3 9]
  [4 7 7]]

 [[8 6 3]
  [1 5 8]
  [8 2 8]
  [8 1 1]
  [4 7 8]
  [7 3 6]]]
[[[6 1 4 1 1 4]
  [8 1 8 8 4 7]]

 [[4 6 4 1 3 7]
  [6 5 2 1 7 3]]

 [[7 3 2 2 9 7]
  [3 8 8 1 8 6]]]


ValueError: cannot reshape array of size 36 into shape (3,)

In [68]:
kernel_size = 3
img = np.random.randint(1, 10, (2, 6, 3))


In [69]:

H, W, C = img.shape
K = int((kernel_size-1)/2)
img = img.transpose(2, 0, 1)
padded_img = np.zeros((C, 2*K+H, 2*K+W))
padded_img[:, K:K+H, K:K+W] = img

filter = np.zeros((kernel_size, kernel_size)) / (kernel_size**2)
filter = filter.reshape(-1, 1)

filtered_img = np.zeros((H, W, C))
for i in range(H):
    for j in range(W):
        window = padded_img[:, i:i+kernel_size, j:j+kernel_size].reshape(C, -1)
        filtered_img[i,j,:] = np.dot(window, filter).reshape(-1)

In [70]:
filtered_img.shape

(2, 6, 3)

In [104]:
import numpy as np

a = np.array([[3, -2], [4,3], [7,8]])
d = np.array([[0, 0], [0,1], [0,0]])
b = np.array([1, 2]).reshape(-1,1)

c = np.dot(a, b)

print(a, b, c, sep='\n\n')
print(a.shape, b.shape)

[[ 3 -2]
 [ 4  3]
 [ 7  8]]

[[1]
 [2]]

[[-1]
 [10]
 [23]]
(3, 2) (2, 1)


In [63]:
kernel_size = 5
K = int((kernel_size-1)/2)

a = np.arange(kernel_size) - K
#b = np.concatenate([a for i in range(kernel_size)], axis=1)
c = np.stack([a for i in range(kernel_size)])
d = np.hstack([a.reshape(-1,1) for i in range(kernel_size)])


print(c, d, sep='\n\n')

[[-2 -1  0  1  2]
 [-2 -1  0  1  2]
 [-2 -1  0  1  2]
 [-2 -1  0  1  2]
 [-2 -1  0  1  2]]

[[-2 -2 -2 -2 -2]
 [-1 -1 -1 -1 -1]
 [ 0  0  0  0  0]
 [ 1  1  1  1  1]
 [ 2  2  2  2  2]]


In [71]:
sigma_s = 3

d = np.arange(kernel_size) - K
dx = np.stack([d for i in range(kernel_size)])
dy = np.hstack([d.reshape(-1,1) for i in range(kernel_size)])
G_s = np.exp( - (dx**2 + dy**2) / (2*sigma_s**2) ).reshape(1, -1)

print(G_s)

[[0.64118039 0.75746513 0.8007374  0.75746513 0.64118039 0.75746513
  0.89483932 0.94595947 0.89483932 0.75746513 0.8007374  0.94595947
  1.         0.94595947 0.8007374  0.75746513 0.89483932 0.94595947
  0.89483932 0.75746513 0.64118039 0.75746513 0.8007374  0.75746513
  0.64118039]]


In [70]:
2*sigma_s**2


18

In [100]:
kernel_size = 3
d = np.arange(kernel_size) - 1
dx = np.stack([d for i in range(kernel_size)])
dy = np.hstack([d.reshape(-1,1) for i in range(kernel_size)])
G_s = np.exp( - (dx**2 + dy**2) / (2*sigma_s**2) ).reshape(1, -1)

img = np.random.randint(1, 10, (3, 3, 3))
img = img.reshape(3, -1)

go = [[1], [2], [1]]
go = np.array(go)

gh = np.exp( - (img - go)**2  / (2*sigma_s**2) )

gl = gh * G_s

gs = gl/gl.sum(axis=1).reshape(-1, 1)

gs = gs[:,0]

print(img, G_s, gl, gs, sep = '\n\n')

[[7 5 3 3 2 7 4 4 2]
 [6 6 9 6 7 5 4 9 4]
 [5 6 1 1 9 2 6 2 1]]

[[0.89483932 0.94595947 0.89483932 0.94595947 1.         0.94595947
  0.89483932 0.94595947 0.89483932]]

[[0.12110333 0.38889556 0.71653131 0.75746513 0.94595947 0.12802169
  0.54274748 0.57375342 0.84648172]
 [0.36787944 0.38889556 0.05881647 0.38889556 0.24935221 0.57375342
  0.71653131 0.06217652 0.71653131]
 [0.36787944 0.23587708 0.89483932 0.94595947 0.0285655  0.89483932
  0.22313016 0.89483932 0.89483932]]

[0.02411956 0.10442719 0.06836931]


In [105]:
img = np.random.randint(1, 10, (3, 5, 5))
img.sum((1,2))

array([127, 126, 106])

In [9]:
import numpy as np

a = 3 + 4j
b = 5 + 6j

o = np.linspace(a, b, 5)

print(o)


[3. +4.j  3.5+4.5j 4. +5.j  4.5+5.5j 5. +6.j ]


In [16]:
rmss = [1.33333, 4.32222, 4.55675]
print(rmss.__format__(":.3f"))

TypeError: unsupported format string passed to list.__format__

In [21]:
np.complex128(np.imag(1))

0j